### ISSUE TITLE
Syntax error?

### ISSUE THREAD

**Issue by chrishoule** [periodic/foundryvtt-summoner#9]
I've installed the module, created the folder named Summons, added the monsters. Gave the player the correct permissions, but I get the following:

"There was an error in your macro syntax"

If I look at the console, I get the following:

ReferenceError: summonerActor is not defined
    anonymous https://assets.forge-vtt.com/bazaar/modules/furnace/2.6.0/Macros/Macros.js line 176 > Function:6
    callScriptMacroFunction https://assets.forge-vtt.com/bazaar/modules/furnace/2.6.0/Macros/Macros.js:179
    renderMacro https://assets.forge-vtt.com/bazaar/modules/furnace/2.6.0/Macros/Macros.js:197
    executeMacro https://assets.forge-vtt.com/bazaar/modules/furnace/2.6.0/Macros/Macros.js:221
    _onClickMacro https://netfrost-merronna.forge-vtt.com/scripts/foundry.js:20566
    jQuery 2
Macros.js:224:25

**Comment by periodic** [comment]
Thanks for reporting an issue!

Most likely it's because you copied from some of my examples that use the `summonerActor` as a placeholder for however you get your own actor.

If you are using Furnace with advanced macros and an item macro then you can just use `actor` (thanks, furnace).  Otherwise you can get them by name like
```javascript
await Summoner.placeAndSummon(
  game.actors.getName("My Character"),
  "Companion",
);
```
